### ISSUE TITLE
Add support for IBM Cloud Object storage

### ISSUE THREAD

**Issue by bonifaido** [IBM-Bluemix/terraform-provider-ibm#10]
The API of COS is not fully compatible with aws_s3_bucket and aws_s3_bucket_object (for example versioning is not supported), so it would be nice to have a resource for creating buckets and objects with this Terraform provider.

**Comment by renier** [comment]
This compatibility work would have to be done in the aws provider for S3 or the openstack provider for swift.

**Comment by mihasya** [comment]
Is the thinking here "S3 compatibility is considered to be a feature of the object store, so just use the S3-compatible provider?" Are there some code snippets somewhere for creating a "bucket" on IBM COS using the built in S3 resources? I've not been able to locate anything concrete yet by googling.

**Comment by davetropeano** [comment]
You can use a `service_instance` resource to create any IBM Cloud service in the catalog, including Cloud Object Storage (COS). You just need the actual service name and the plan name. You can get these with a `bx cf marketplace` or other similar commands. 

The service name for COS is `cloud-object-storage` and the available plan names are `Lite` and `Premium`. Case matters with these when you provision the resource.

This does not provide the ability to create buckets, etc. That would fall under the typical topic of deploying artifacts which is not typically the intent of terraform. Generally we've taken the view of limiting the provider to provisioning resources and not creating objects within those resources. 

We are looking at providing "first class" support for COS as its own resource type. But this is still very much in discussion.

**Comment by spkane** [comment]
Assuming that the IBM COS storage account has been created in the console, it feels like something close to this should work in theory:

```
# Configure the IBM Cloud Provider

# Currently the auth is pulled in via the env vars:
# BM_API_KEY, SL_USERNAME, and SL_API_KEY
provider "ibm" {
  region = "eu-de"
}

provider "aws" {
  # I think the region must be valid for AWS
  # Butis likely ignored since we use a custom endpoint.
  region  = "us-east-1"
  profile = "ibm-cloud-de"
  endpoints {
    s3 = "http://s3.fra-eu-geo.objectstorage.softlayer.net"
  }
}

# Swift related (NOT S3 related from what I can tell)
#resource "ibm_object_storage_account" "test" {
#}

resource "aws_s3_bucket" "test" {
  bucket = "test"
}
```

**Comment by davetropeano** [comment]
@spkane Thanks.

I'll admit to being lazy and not trying this but one of my initial concerns is whether you can have an aws provider statement without providing the needed credentials.

You are correct that `object_storage_account` just refers to the (legacy) Softlayer object storage based on Swift and not the newer IBM COS service. Naming really gets in the way here.

I'll get to trying this out but I am not sure it'll work without a set of aws credentials which an IBM Cloud user may not have.

**Comment by davetropeano** [comment]
Thanks for the details. We will get one of the development team looking at this. @ashishth09

**Comment by vkalangu** [comment]
Dave @sakshiag looking into this

**Comment by chelsey** [comment]
Hi there @ashishth09 @sakshiag -- any update on this?

**Comment by sakshiag** [comment]
@chelsey : An IBM COS System may be configured in either ‘Vault’ or ‘Container’ mode. Some operations, such as tagging and versioning, are not available in ‘Container’ mode. I guess you had configured the COS in container mode which is leading to the error.
https://www.ibm.com/support/knowledgecenter/en/STXNRM_3.11.1/coss.doc/api_ssec.html

**Comment by chelsey** [comment]
@sakshiag Correct, it is configured in container mode. How do I bypass that error for container mode systems?

**Comment by sakshiag** [comment]
@chelsey : Looking into this.. will get back to you ..

**Comment by sakshiag** [comment]
I looked into the aws provider, they are using the versioning api's which are causing this issue....
For now, I don't see the way to bypass it using the container mode..
Are you able to do it using api or cli?

**Comment by spkane** [comment]
Might be worth a PR to the AWS provider, so that this can be disabled.

**Comment by KyungmoIBM** [comment]
@davetropeano, Your suggestion(https://github.com/negronjl/terraform-provider-s3) works fine with this;
provider "s3" {
  s3_server        = "s3-api.us-geo.objectstorage.softlayer.net"
  s3_region        = "us-standard" #it's a storage class, ie us-vault 
  s3_access_key    = "********"
  s3_secret_key    = "********"
  s3_api_signature = "v2"
  s3_ssl           = true
  s3_debug         = true
}

resource "s3_bucket" "b" {
  bucket = "new-bucket-name"
} 

And @chelsey, the error occurs by 'aws_s3_bucket.test'. aws provider performs testing after creating bucket, before destroying bucket. It is not avoidable in IBM Cloud at the moment because versioning is not available yet...
