### ISSUE TITLE
Expose the list of subnets of an ibm_container_cluster as an attribute

### ISSUE THREAD

**Issue by bonifaido** [IBM-Bluemix/terraform-provider-ibm#31]
I know there is an API endpoint for this: https://us-south.containers.bluemix.net/swagger-api/#!/clusters/GetCluster
This information would be really helpful in certain situations, like setting up firewalls:
```json
"vlans": [
    {
      "id": "string",
      "subnets": [
        {
          "cidr": "string",
          "id": "string",
          "ips": [
            "string"
          ],
          "is_byoip": true,
          "is_public": true
        }
      ]
    }
  ]
```
Can we add this to the resource's attributes?

**Comment by bonifaido** [comment]
I just checked the go API and this information is unfortunately not parsed there: https://github.com/IBM-Bluemix/bluemix-go/blob/master/api/container/containerv1/clusters.go

**Comment by Praveengostu** [comment]
@bonifaido Looks like this was a new version from cluster API. When we developed cluster we had taken care  of what was there. we will take this was an enhancement to the cluster datasource  "ibm_container_cluster".
