### ISSUE TITLE
unable to order bare_metal servers with the latest code, v0.4 does not send user_metadata

### ISSUE THREAD

**Issue by lospringliu** [IBM-Bluemix/terraform-provider-ibm#36]
message for latest code:
ibm_compute_bare_metal.masters: Error ordering bare metal server: SoftLayer_Exception_Public: Could not place order. An uncaught exception was encountered. Please contact Sales. (HTTP 500)

**Comment by ashishth09** [comment]
Hi @lospringliu , by latest you mean the master of the current repo or the tag v0.4, Could you please  attach the trace here. You can run again by `export TF_LOG=trace`

**Comment by lospringliu** [comment]
I built the provider using master branch and applied a bare metal, this time I got the user_metadata with https://api.service.softlayer.com/rest/v3/SoftLayer_Resource_Metadata/UserMetadata.txt

false issue
