### ISSUE TITLE
[standalone provider built from master branch] create bare metal issue 

### ISSUE THREAD

**Issue by lospringliu** [IBM-Bluemix/terraform-provider-ibm#42]
I created a bare metal with a presetconfiguration in datacenter **tor01** in one repository,  I then create another bare metal with the same presetconfiguration, but in different datacenter saying **dal01** , it shows creation in seconds. But actually it did not create a new one, but take the existing one and changed the datacenter.

**************************************************************************
xinchuns-mbp:spectrum-schematics-cluster xcliuca$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + ibm_compute_bare_metal.masters
      id:                      <computed>
      block_storage_ids.#:     <computed>
      datacenter:              "dal01"
      domain:                  "domain.com"
      file_storage_ids.#:      <computed>
      fixed_config_preset:     "S1270_32GB_2X960GBSSD_NORAID"
      hostname:                "master0"
      hourly_billing:          "true"
      memory:                  <computed>
      network_speed:           "1000"
      os_reference_code:       "UBUNTU_16_64"
      post_install_script_uri: "https://raw.githubusercontent.com/xcliu-ca/spectrum-schematics-cluster/dev/scripts/ibm_spectrum_computing_deploy.sh"
      private_ipv4_address:    <computed>
      private_network_only:    "false"
      private_subnet:          <computed>
      private_vlan_id:         <computed>
      public_bandwidth:        <computed>
      public_ipv4_address:     <computed>
      public_subnet:           <computed>
      public_vlan_id:          <computed>
      redundant_network:       "false"
      redundant_power_supply:  <computed>
      ssh_key_ids.#:           <computed>
      tcp_monitoring:          "false"
      unbonded_network:        "false"
      user_metadata:           "#!/bin/bash\n\ndeclare -i numbercomputes=0\nuseintranet=false\ndomain=domain.com\nproduct=cws\nversion=latest\nrole=master\nclusteradmin=egoadmin\nclustername=symcluster\nentitlement=ZWdvX2Jhc2UgICAzLjUgICAzMS8xMi8yMDE3ICAgKCkgICAoKSAgICgpICAgMWRkNTMwMzhjNjBkYmI1ZmZjMTNjZGNjMzA4MGVmYWYyOGVlYjk1Mgpjb25kdWN0b3Jfc3BhcmsgICAyLjIuMCAgIDMxLzEyLzIwMTcgICAoKSAgICgpICAgKCkgICAzZDVjYzk3MWZjNTNhYjIxNGYxZGM2YzcwYjc0YjI3MmMxNDJjNTc0Cg==\nfunctionsfile=https://raw.githubusercontent.com/xcliu-ca/spectrum-schematics-cluster/dev/scripts/cws.sh\n"

  + ibm_compute_ssh_key.ssh_compute_key
      id:                      <computed>
      fingerprint:             <computed>
      label:                   "ssh_compute_key_xcliu"
      notes:                   "ssh key for cluster hosts xcliu"
      public_key:              "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD1M+TrebO7p8q96jqW8TGjb1mahWvXCmdcx4t++slnBkw/NZt0P8da+3/3MLjR52k86lDjlscUkYf1n2ibTZCq9z2a2ZkhXgyv/v5qNz4WrKo7qDYv/1FBujg6HPy2TEi6jFp8NGWyJlHh88COfldgx9q4bglQ8gO0MLNr8gbi5AfdrnKx3LnR4XGc4ARpuxqUuQYSQ9UoCm+tOlq43KUOtsfeIB09g5c+SYutCVrAOLOTRBGCTHBFAIqZF/txWKT3QDGIE2OpdV2BOrDQ3eTD06FR4ocwV+zc8gIIWMVC7P2TLDurbcC4qjYRg00YfM0H+hNNO2nq2n+nO6uEhKl xcliu@xinchunliu"

Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

xinchuns-mbp:spectrum-schematics-cluster xcliuca$ terraform apply
ibm_compute_ssh_key.ssh_compute_key: Creating...
  fingerprint: "" => "<computed>"
  label:       "" => "ssh_compute_key_xcliu"
  notes:       "" => "ssh key for cluster hosts xcliu"
  public_key:  "" => "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD1M+TrebO7p8q96jqW8TGjb1mahWvXCmdcx4t++slnBkw/NZt0P8da+3/3MLjR52k86lDjlscUkYf1n2ibTZCq9z2a2ZkhXgyv/v5qNz4WrKo7qDYv/1FBujg6HPy2TEi6jFp8NGWyJlHh88COfldgx9q4bglQ8gO0MLNr8gbi5AfdrnKx3LnR4XGc4ARpuxqUuQYSQ9UoCm+tOlq43KUOtsfeIB09g5c+SYutCVrAOLOTRBGCTHBFAIqZF/txWKT3QDGIE2OpdV2BOrDQ3eTD06FR4ocwV+zc8gIIWMVC7P2TLDurbcC4qjYRg00YfM0H+hNNO2nq2n+nO6uEhKl xcliu@xinchunliu"
ibm_compute_ssh_key.ssh_compute_key: Creation complete after 1s (ID: 978913)
ibm_compute_bare_metal.masters: Creating...
  block_storage_ids.#:     "" => "<computed>"
  datacenter:              "" => "dal01"
  domain:                  "" => "domain.com"
  file_storage_ids.#:      "" => "<computed>"
  fixed_config_preset:     "" => "S1270_32GB_2X960GBSSD_NORAID"
  hostname:                "" => "master0"
  hourly_billing:          "" => "true"
  memory:                  "" => "<computed>"
  network_speed:           "" => "1000"
  os_reference_code:       "" => "UBUNTU_16_64"
  post_install_script_uri: "" => "https://raw.githubusercontent.com/xcliu-ca/spectrum-schematics-cluster/dev/scripts/ibm_spectrum_computing_deploy.sh"
  private_ipv4_address:    "" => "<computed>"
  private_network_only:    "" => "false"
  private_subnet:          "" => "<computed>"
  private_vlan_id:         "" => "<computed>"
  public_bandwidth:        "" => "<computed>"
  public_ipv4_address:     "" => "<computed>"
  public_subnet:           "" => "<computed>"
  public_vlan_id:          "" => "<computed>"
  redundant_network:       "" => "false"
  redundant_power_supply:  "" => "<computed>"
  ssh_key_ids.#:           "" => "1"
  ssh_key_ids.0:           "" => "978913"
  tcp_monitoring:          "" => "false"
  unbonded_network:        "" => "false"
  user_metadata:           "" => "#!/bin/bash\n\ndeclare -i numbercomputes=0\nuseintranet=false\ndomain=domain.com\nproduct=cws\nversion=latest\nrole=master\nclusteradmin=egoadmin\nclustername=symcluster\nentitlement=ZWdvX2Jhc2UgICAzLjUgICAzMS8xMi8yMDE3ICAgKCkgICAoKSAgICgpICAgMWRkNTMwMzhjNjBkYmI1ZmZjMTNjZGNjMzA4MGVmYWYyOGVlYjk1Mgpjb25kdWN0b3Jfc3BhcmsgICAyLjIuMCAgIDMxLzEyLzIwMTcgICAoKSAgICgpICAgKCkgICAzZDVjYzk3MWZjNTNhYjIxNGYxZGM2YzcwYjc0YjI3MmMxNDJjNTc0Cg==\nfunctionsfile=https://raw.githubusercontent.com/xcliu-ca/spectrum-schematics-cluster/dev/scripts/cws.sh\n"
ibm_compute_bare_metal.masters: Still creating... (10s elapsed)
ibm_compute_bare_metal.masters: Creation complete after 19s (ID: 502052)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

cluster_master_ip = 158.85.106.39
cluster_web_interface = https://158.85.106.39:8443/platform
symphony_dehost_ip =
xinchuns-mbp:spectrum-schematics-cluster xcliuca$ terraform show 
ibm_compute_bare_metal.masters:
  id = 502052
  block_storage_ids.# = 0
  datacenter = tor01
  domain = domain.com
  file_storage_ids.# = 0
  fixed_config_preset = S1270_32GB_2X960GBSSD_NORAID
  hostname = master0
  hourly_billing = true
  memory = 32
  network_speed = 100
  notes = 
  os_reference_code = UBUNTU_16_64
  post_install_script_uri = https://raw.githubusercontent.com/xcliu-ca/spectrum-schematics-cluster/dev/scripts/ibm_spectrum_computing_deploy.sh
  private_ipv4_address = 10.115.181.75
  private_network_only = false
  public_ipv4_address = 158.85.106.39
  redundant_network = false
  redundant_power_supply = false
  ssh_key_ids.# = 1
  ssh_key_ids.0 = 978913
  tcp_monitoring = false
  unbonded_network = false
  user_metadata = #!/bin/bash

declare -i numbercomputes=1
useintranet=false
domain=domain.com
echo test > /root/metadata

ibm_compute_ssh_key.ssh_compute_key:
  id = 978913
  fingerprint = 98:b7:4b:95:b3:2c:79:f6:3a:f8:91:70:9b:44:36:4a
  label = ssh_compute_key_xcliu
  notes = ssh key for cluster hosts xcliu
  public_key = ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD1M+TrebO7p8q96jqW8TGjb1mahWvXCmdcx4t++slnBkw/NZt0P8da+3/3MLjR52k86lDjlscUkYf1n2ibTZCq9z2a2ZkhXgyv/v5qNz4WrKo7qDYv/1FBujg6HPy2TEi6jFp8NGWyJlHh88COfldgx9q4bglQ8gO0MLNr8gbi5AfdrnKx3LnR4XGc4ARpuxqUuQYSQ9UoCm+tOlq43KUOtsfeIB09g5c+SYutCVrAOLOTRBGCTHBFAIqZF/txWKT3QDGIE2OpdV2BOrDQ3eTD06FR4ocwV+zc8gIIWMVC7P2TLDurbcC4qjYRg00YfM0H+hNNO2nq2n+nO6uEhKl xcliu@xinchunliu

Outputs:

cluster_master_ip = 158.85.106.39
cluster_web_interface = https://158.85.106.39:8443/platform
symphony_dehost_ip =

**Comment by ashishth09** [comment]
Hi @lospringliu , 

Thanks for submitting the issue. Looks like a genuine problem.

Did you really mean to use the same host and domain name for bare metals in the different data center?
SoftLayer won't really stop you from doing this but just wanted to check if this fits your use case.

As per the current code we are scanning the hostname and domain of the server and return that. This was based on an earlier restriction on the API. Hence you see the issue.

So as a workaround you can use different hostname/domain to proceed.

**Comment by ashishth09** [comment]
I will close this based on the actual use case here.
