### ISSUE TITLE
Adding a private portable subnet to a cluster never completes

### ISSUE THREAD

**Issue by mmajis** [IBM-Bluemix/terraform-provider-ibm#51]
Adding a private subnet to a cluster does not create an ingress subdomain and secret. The cluster resource waits for those when adding a subnet and subsequently never completes.

https://github.com/IBM-Bluemix/terraform-provider-ibm/blob/cd7ddb50ab39a0c6e5139a08d08a7632971e27a5/ibm/resource_ibm_container_cluster.go#L597

A workaround is to make sure there's always a public subnet in the list of subnets...

**Comment by Praveengostu** [comment]
Will avoid calling waiting for subnets if only a private subnet is added to the cluster

**Comment by ashishth09** [comment]
Closed in #54
