### ISSUE TITLE
[v0.5.0] create bare metal failed [Order is missing Power Supply]

### ISSUE THREAD

**Issue by lospringliu** [IBM-Bluemix/terraform-provider-ibm#58]
xinchuns-mbp:spectrum-schematics-cluster xcliuca$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

ibm_compute_ssh_key.ssh_compute_key: Refreshing state... (ID: 996651)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + ibm_compute_bare_metal.masters
      id:                      <computed>
      block_storage_ids.#:     <computed>
      datacenter:              "tor01"
      domain:                  "domain.com"
      file_storage_ids.#:      <computed>
      fixed_config_preset:     "S1270_32GB_2X960GBSSD_NORAID"
      hostname:                "master0"
      hourly_billing:          "true"
      memory:                  <computed>
      network_speed:           "1000"
      os_reference_code:       "UBUNTU_16_64"
      post_install_script_uri: "https://raw.githubusercontent.com/IBMSpectrumComputing/spectrum-schematics-cluster/master/scripts/ibm_spectrum_computing_deploy.sh"
      private_ipv4_address:    <computed>
      private_network_only:    "false"
      private_subnet:          <computed>
      private_vlan_id:         <computed>
      public_bandwidth:        <computed>
      public_ipv4_address:     <computed>
      public_subnet:           <computed>
      public_vlan_id:          <computed>
      redundant_network:       "false"
      redundant_power_supply:  <computed>
      ssh_key_ids.#:           "1"
      ssh_key_ids.0:           "996651"
      tcp_monitoring:          "false"
      unbonded_network:        "false"
      user_metadata:           "#!/bin/bash\n\ndeclare -i numbercomputes=0\nuseintranet=false\ndomain=domain.com\n"

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

xinchuns-mbp:spectrum-schematics-cluster xcliuca$ terraform apply
ibm_compute_ssh_key.ssh_compute_key: Refreshing state... (ID: 996651)
ibm_compute_bare_metal.masters: Creating...
  block_storage_ids.#:     "" => "<computed>"
  datacenter:              "" => "tor01"
  domain:                  "" => "domain.com"
  file_storage_ids.#:      "" => "<computed>"
  fixed_config_preset:     "" => "S1270_32GB_2X960GBSSD_NORAID"
  hostname:                "" => "master0"
  hourly_billing:          "" => "true"
  memory:                  "" => "<computed>"
  network_speed:           "" => "1000"
  os_reference_code:       "" => "UBUNTU_16_64"
  post_install_script_uri: "" => "https://raw.githubusercontent.com/IBMSpectrumComputing/spectrum-schematics-cluster/master/scripts/ibm_spectrum_computing_deploy.sh"
  private_ipv4_address:    "" => "<computed>"
  private_network_only:    "" => "false"
  private_subnet:          "" => "<computed>"
  private_vlan_id:         "" => "<computed>"
  public_bandwidth:        "" => "<computed>"
  public_ipv4_address:     "" => "<computed>"
  public_subnet:           "" => "<computed>"
  public_vlan_id:          "" => "<computed>"
  redundant_network:       "" => "false"
  redundant_power_supply:  "" => "<computed>"
  ssh_key_ids.#:           "" => "1"
  ssh_key_ids.0:           "" => "996651"
  tcp_monitoring:          "" => "false"
  unbonded_network:        "" => "false"
  user_metadata:           "" => "#!/bin/bash\n\ndeclare -i numbercomputes=0\nuseintranet=false\ndomain=domain.com\n"
Error applying plan:

1 error(s) occurred:

* ibm_compute_bare_metal.masters: 1 error(s) occurred:

* ibm_compute_bare_metal.masters: Error ordering bare metal server: SoftLayer_Exception_Order_MissingCategory: **Order is missing the following category: Power Supply. (HTTP 500)**
{Entity:{} BigDataOrderFlag:<nil> BillingInformation:<nil> BillingOrderItemId:<nil> CancelUrl:<nil> ComplexType:0xc420423210 ContainerIdentifier:<nil> ContainerSplHash:<nil> CurrencyShortName:<nil> DeviceFingerprintId:<nil> DisplayLayerSessionId:<nil> ExtendedHardwareTesting:<nil> FlexibleCreditProgramPrice:<nil> Hardware:[{Entity:{} Account:<nil> AccountId:<nil> ActiveComponentCount:<nil> ActiveComponents:[] ActiveNetworkMonitorIncident:[] ActiveNetworkMonitorIncidentCount:<nil> AllPowerComponentCount:<nil> AllPowerComponents:[] AllowedHost:<nil> AllowedNetworkStorage:[] AllowedNetworkStorageCount:<nil> AllowedNetworkStorageReplicaCount:<nil> AllowedNetworkStorageReplicas:[] AntivirusSpywareSoftwareComponent:<nil> AttributeCount:<nil> Attributes:[] AverageDailyPublicBandwidthUsage:<nil> BackendNetworkComponentCount:<nil> BackendNetworkComponents:[] BackendRouterCount:<nil> BackendRouters:[] BandwidthAllocation:<nil> BandwidthAllotmentDetail:<nil> BareMetalInstanceFlag:<nil> BenchmarkCertificationCount:<nil> BenchmarkCertifications:[] BillingItem:<nil> BillingItemFlag:<nil> BlockCancelBecauseDisconnectedFlag:<nil> BusinessContinuanceInsuranceFlag:<nil> ChildrenHardware:[] ChildrenHardwareCount:<nil> ComponentCount:<nil> Components:[] ContinuousDataProtectionSoftwareComponent:<nil> CurrentBillableBandwidthUsage:<nil> Datacenter:<nil> DatacenterName:<nil> Domain:0xc42027e770 DownlinkHardware:[] DownlinkHardwareCount:<nil> DownlinkNetworkHardware:[] DownlinkNetworkHardwareCount:<nil> DownlinkServerCount:<nil> DownlinkServers:[] DownlinkVirtualGuestCount:<nil> DownlinkVirtualGuests:[] DownstreamHardwareBindingCount:<nil> DownstreamHardwareBindings:[] DownstreamNetworkHardware:[] DownstreamNetworkHardwareCount:<nil> DownstreamNetworkHardwareWithIncidentCount:<nil> DownstreamNetworkHardwareWithIncidents:[] DownstreamServerCount:<nil> DownstreamServers:[] DownstreamVirtualGuestCount:<nil> DownstreamVirtualGuests:[] DriveControllerCount:<nil> DriveControllers:[] EvaultNetworkStorage:[] EvaultNetworkStorageCount:<nil> FirewallServiceComponent:<nil> FixedConfigurationPreset:0xc4204da000 FrontendNetworkComponentCount:<nil> FrontendNetworkComponents:[] FrontendRouterCount:<nil> FrontendRouters:[] FullyQualifiedDomainName:<nil> GlobalIdentifier:<nil> HardDriveCount:<nil> HardDrives:[] HardwareChassis:<nil> HardwareFunction:<nil> HardwareFunctionDescription:<nil> HardwareStatus:<nil> HardwareStatusId:<nil> HasTrustedPlatformModuleBillingItemFlag:<nil> HostIpsSoftwareComponent:<nil> Hostname:0xc42000f940 HourlyBillingFlag:<nil> Id:<nil> InboundBandwidthUsage:<nil> InboundPublicBandwidthUsage:<nil> LastTransaction:<nil> LatestNetworkMonitorIncident:<nil> Location:<nil> LocationPathString:<nil> LockboxNetworkStorage:<nil> ManagedResourceFlag:<nil> ManufacturerSerialNumber:<nil> Memory:[] MemoryCapacity:<nil> MemoryCount:<nil> MetricTrackingObject:<nil> MonitoringAgentCount:<nil> MonitoringAgents:[] MonitoringRobot:<nil> MonitoringServiceComponent:<nil> MonitoringServiceEligibilityFlag:<nil> MonitoringServiceFlag:<nil> Motherboard:<nil> NetworkCardCount:<nil> NetworkCards:[] NetworkComponentCount:<nil> NetworkComponents:[] NetworkGatewayMember:<nil> NetworkGatewayMemberFlag:<nil> NetworkManagementIpAddress:<nil> NetworkMonitorAttachedDownHardware:[] NetworkMonitorAttachedDownHardwareCount:<nil> NetworkMonitorAttachedDownVirtualGuestCount:<nil> NetworkMonitorAttachedDownVirtualGuests:[] NetworkMonitorCount:<nil> NetworkMonitorIncidentCount:<nil> NetworkMonitorIncidents:[] NetworkMonitors:[] NetworkStatus:<nil> NetworkStatusAttribute:<nil> NetworkStorage:[] NetworkStorageCount:<nil> NetworkVlanCount:<nil> NetworkVlans:[] NextBillingCycleBandwidthAllocation:<nil> Notes:<nil> NotesHistory:[] NotesHistoryCount:<nil> OperatingSystem:<nil> OperatingSystemReferenceCode:<nil> OutboundBandwidthUsage:<nil> OutboundPublicBandwidthUsage:<nil> ParentHardware:<nil> PointOfPresenceLocation:<nil> PostInstallScriptUri:<nil> PowerComponentCount:<nil> PowerComponents:[] PowerSupply:[] PowerSupplyCount:<nil> PrimaryBackendIpAddress:<nil> PrimaryBackendNetworkComponent:<nil> PrimaryIpAddress:<nil> PrimaryNetworkComponent:<nil> PrivateNetworkOnlyFlag:<nil> ProcessorCoreAmount:<nil> ProcessorCount:<nil> ProcessorPhysicalCoreAmount:<nil> Processors:[] ProvisionDate:<nil> Rack:<nil> RaidControllerCount:<nil> RaidControllers:[] RecentEventCount:<nil> RecentEvents:[] RemoteManagementAccountCount:<nil> RemoteManagementAccounts:[] RemoteManagementComponent:<nil> ResourceConfigurationCount:<nil> ResourceConfigurations:[] ResourceGroupCount:<nil> ResourceGroupMemberReferenceCount:<nil> ResourceGroupMemberReferences:[] ResourceGroupRoleCount:<nil> ResourceGroupRoles:[] ResourceGroups:[] RouterCount:<nil> Routers:[] ScaleAssetCount:<nil> ScaleAssets:[] SecurityScanRequestCount:<nil> SecurityScanRequests:[] SerialNumber:<nil> ServerRoom:<nil> ServiceProvider:<nil> ServiceProviderId:<nil> ServiceProviderResourceId:<nil> SoftwareComponentCount:<nil> SoftwareComponents:[] SparePoolBillingItem:<nil> SshKeyCount:<nil> SshKeys:[{Entity:{} Account:<nil> BlockDeviceTemplateGroupCount:<nil> BlockDeviceTemplateGroups:[] CreateDate:<nil> Fingerprint:<nil> Id:0xc420422768 Key:<nil> Label:<nil> ModifyDate:<nil> Notes:<nil> SoftwarePasswordCount:<nil> SoftwarePasswords:[]}] StorageNetworkComponentCount:<nil> StorageNetworkComponents:[] TagReferenceCount:<nil> TagReferences:[] TopLevelLocation:<nil> UpgradeRequest:<nil> UplinkHardware:<nil> UplinkNetworkComponentCount:<nil> UplinkNetworkComponents:[] UserData:[{Entity:{} HardwareAttributeType:<nil> HardwareAttributeTypeId:<nil> Id:<nil> Value:0xc420388f80}] UserDataCount:<nil> VirtualChassis:<nil> VirtualChassisSiblingCount:<nil> VirtualChassisSiblings:[] VirtualHost:<nil> VirtualLicenseCount:<nil> VirtualLicenses:[] VirtualRack:<nil> VirtualRackId:<nil> VirtualRackName:<nil> VirtualizationPlatform:<nil>}] ImageTemplateGlobalIdentifier:<nil> ImageTemplateId:<nil> IsManagedOrder:<nil> ItemCategoryQuestionAnswers:[] Location:0xc42000fc80 LocationObject:<nil> Message:<nil> OrderContainers:[] OrderHostnames:[] OrderVerificationExceptions:[] PackageId:0xc42000fcd0 PaymentType:<nil> PostTaxRecurring:<nil> PostTaxRecurringHourly:<nil> PostTaxRecurringMonthly:<nil> PostTaxSetup:<nil> PreTaxRecurring:<nil> PreTaxRecurringHourly:<nil> PreTaxRecurringMonthly:<nil> PreTaxSetup:<nil> PresaleEvent:<nil> PresetId:0xc42000fd80 Prices:[{Entity:{} AccountRestrictionCount:<nil> AccountRestrictions:[] AttributeCount:<nil> Attributes:[] BigDataOsJournalDiskFlag:<nil> BundleReferenceCount:<nil> BundleReferences:[] CapacityRestrictionMaximum:<nil> CapacityRestrictionMinimum:<nil> CapacityRestrictionType:<nil> Categories:[] CategoryCount:<nil> CurrentPriceFlag:<nil> DefinedSoftwareLicenseFlag:<nil> HourlyRecurringFee:0xc4201012a0 Id:0xc4201016f8 Inventory:[] InventoryCount:<nil> Item:0xc42057a380 ItemId:<nil> LaborFee:<nil> LocationGroupId:<nil> OnSaleFlag:<nil> OneTimeFee:<nil> OneTimeFeeTax:<nil> OrderOptions:[] OrderPremiumCount:<nil> OrderPremiums:[] PackageCount:<nil> PackageReferenceCount:<nil> PackageReferences:[] Packages:[] PresetConfigurationCount:<nil> PresetConfigurations:[] PricingLocationGroup:<nil> ProratedRecurringFee:<nil> ProratedRecurringFeeTax:<nil> Quantity:<nil> RecurringFee:0xc420101728 RecurringFeeTax:<nil> RequiredCoreCount:<nil> SetupFee:<nil> Sort:<nil> UsageRate:<nil>} {Entity:{} AccountRestrictionCount:<nil> AccountRestrictions:[] AttributeCount:<nil> Attributes:[] BigDataOsJournalDiskFlag:<nil> BundleReferenceCount:<nil> BundleReferences:[] CapacityRestrictionMaximum:<nil> CapacityRestrictionMinimum:<nil> CapacityRestrictionType:<nil> Categories:[] CategoryCount:<nil> CurrentPriceFlag:<nil> DefinedSoftwareLicenseFlag:<nil> HourlyRecurringFee:0xc420101738 Id:0xc420101808 Inventory:[] InventoryCount:<nil> Item:0xc42028bc00 ItemId:<nil> LaborFee:<nil> LocationGroupId:<nil> OnSaleFlag:<nil> OneTimeFee:<nil> OneTimeFeeTax:<nil> OrderOptions:[] OrderPremiumCount:<nil> OrderPremiums:[] PackageCount:<nil> PackageReferenceCount:<nil> PackageReferences:[] Packages:[] PresetConfigurationCount:<nil> PresetConfigurations:[] PricingLocationGroup:<nil> ProratedRecurringFee:<nil> ProratedRecurringFeeTax:<nil> Quantity:<nil> RecurringFee:0xc4201018a8 RecurringFeeTax:<nil> RequiredCoreCount:<nil> SetupFee:<nil> Sort:<nil> UsageRate:<nil>} {Entity:{} AccountRestrictionCount:<nil> AccountRestrictions:[] AttributeCount:<nil> Attributes:[] BigDataOsJournalDiskFlag:<nil> BundleReferenceCount:<nil> BundleReferences:[] CapacityRestrictionMaximum:<nil> CapacityRestrictionMinimum:<nil> CapacityRestrictionType:<nil> Categories:[] CategoryCount:<nil> CurrentPriceFlag:<nil> DefinedSoftwareLicenseFlag:<nil> HourlyRecurringFee:0xc4201525c8 Id:0xc420152638 Inventory:[] InventoryCount:<nil> Item:0xc4205de000 ItemId:<nil> LaborFee:<nil> LocationGroupId:<nil> OnSaleFlag:<nil> OneTimeFee:<nil> OneTimeFeeTax:<nil> OrderOptions:[] OrderPremiumCount:<nil> OrderPremiums:[] PackageCount:<nil> PackageReferenceCount:<nil> PackageReferences:[] Packages:[] PresetConfigurationCount:<nil> PresetConfigurations:[] PricingLocationGroup:<nil> ProratedRecurringFee:<nil> ProratedRecurringFeeTax:<nil> Quantity:<nil> RecurringFee:<nil> RecurringFeeTax:<nil> RequiredCoreCount:<nil> SetupFee:<nil> Sort:<nil> UsageRate:<nil>} {Entity:{} AccountRestrictionCount:<nil> AccountRestrictions:[] AttributeCount:<nil> Attributes:[] BigDataOsJournalDiskFlag:<nil> BundleReferenceCount:<nil> BundleReferences:[] CapacityRestrictionMaximum:<nil> CapacityRestrictionMinimum:<nil> CapacityRestrictionType:<nil> Categories:[] CategoryCount:<nil> CurrentPriceFlag:<nil> DefinedSoftwareLicenseFlag:<nil> HourlyRecurringFee:0xc420152678 Id:0xc42029e048 Inventory:[] InventoryCount:<nil> Item:0xc4205dfc00 ItemId:<nil> LaborFee:<nil> LocationGroupId:<nil> OnSaleFlag:<nil> OneTimeFee:<nil> OneTimeFeeTax:<nil> OrderOptions:[] OrderPremiumCount:<nil> OrderPremiums:[] PackageCount:<nil> PackageReferenceCount:<nil> PackageReferences:[] Packages:[] PresetConfigurationCount:<nil> PresetConfigurations:[] PricingLocationGroup:<nil> ProratedRecurringFee:<nil> ProratedRecurringFeeTax:<nil> Quantity:<nil> RecurringFee:0xc42029e078 RecurringFeeTax:<nil> RequiredCoreCount:<nil> SetupFee:<nil> Sort:<nil> UsageRate:<nil>} {Entity:{} AccountRestrictionCount:<nil> AccountRestrictions:[] AttributeCount:<nil> Attributes:[] BigDataOsJournalDiskFlag:<nil> BundleReferenceCount:<nil> BundleReferences:[] CapacityRestrictionMaximum:<nil> CapacityRestrictionMinimum:<nil> CapacityRestrictionType:<nil> Categories:[] CategoryCount:<nil> CurrentPriceFlag:<nil> DefinedSoftwareLicenseFlag:<nil> HourlyRecurringFee:0xc42029e108 Id:0xc42029e188 Inventory:[] InventoryCount:<nil> Item:0xc420284700 ItemId:<nil> LaborFee:<nil> LocationGroupId:<nil> OnSaleFlag:<nil> OneTimeFee:<nil> OneTimeFeeTax:<nil> OrderOptions:[] OrderPremiumCount:<nil> OrderPremiums:[] PackageCount:<nil> PackageReferenceCount:<nil> PackageReferences:[] Packages:[] PresetConfigurationCount:<nil> PresetConfigurations:[] PricingLocationGroup:<nil> ProratedRecurringFee:<nil> ProratedRecurringFeeTax:<nil> Quantity:<nil> RecurringFee:0xc42029f3d8 RecurringFeeTax:<nil> RequiredCoreCount:<nil> SetupFee:<nil> Sort:<nil> UsageRate:<nil>} {Entity:{} AccountRestrictionCount:<nil> AccountRestrictions:[] AttributeCount:<nil> Attributes:[] BigDataOsJournalDiskFlag:<nil> BundleReferenceCount:<nil> BundleReferences:[] CapacityRestrictionMaximum:<nil> CapacityRestrictionMinimum:<nil> CapacityRestrictionType:<nil> Categories:[] CategoryCount:<nil> CurrentPriceFlag:<nil> DefinedSoftwareLicenseFlag:<nil> HourlyRecurringFee:0xc42029f4b0 Id:0xc42033c0d0 Inventory:[] InventoryCount:<nil> Item:0xc42058ce00 ItemId:<nil> LaborFee:<nil> LocationGroupId:<nil> OnSaleFlag:<nil> OneTimeFee:<nil> OneTimeFeeTax:<nil> OrderOptions:[] OrderPremiumCount:<nil> OrderPremiums:[] PackageCount:<nil> PackageReferenceCount:<nil> PackageReferences:[] Packages:[] PresetConfigurationCount:<nil> PresetConfigurations:[] PricingLocationGroup:<nil> ProratedRecurringFee:<nil> ProratedRecurringFeeTax:<nil> Quantity:<nil> RecurringFee:0xc42033c5f0 RecurringFeeTax:<nil> RequiredCoreCount:<nil> SetupFee:<nil> Sort:<nil> UsageRate:<nil>} {Entity:{} AccountRestrictionCount:<nil> AccountRestrictions:[] AttributeCount:<nil> Attributes:[] BigDataOsJournalDiskFlag:<nil> BundleReferenceCount:<nil> BundleReferences:[] CapacityRestrictionMaximum:<nil> CapacityRestrictionMinimum:<nil> CapacityRestrictionType:<nil> Categories:[] CategoryCount:<nil> CurrentPriceFlag:<nil> DefinedSoftwareLicenseFlag:<nil> HourlyRecurringFee:0xc42033c6d0 Id:0xc42033c6e0 Inventory:[] InventoryCount:<nil> Item:0xc4205c4e00 ItemId:<nil> LaborFee:<nil> LocationGroupId:<nil> OnSaleFlag:<nil> OneTimeFee:<nil> OneTimeFeeTax:<nil> OrderOptions:[] OrderPremiumCount:<nil> OrderPremiums:[] PackageCount:<nil> PackageReferenceCount:<nil> PackageReferences:[] Packages:[] PresetConfigurationCount:<nil> PresetConfigurations:[] PricingLocationGroup:<nil> ProratedRecurringFee:<nil> ProratedRecurringFeeTax:<nil> Quantity:<nil> RecurringFee:0xc42033c750 RecurringFeeTax:<nil> RequiredCoreCount:<nil> SetupFee:<nil> Sort:<nil> UsageRate:<nil>}] PrimaryDiskPartitionId:<nil> Priorities:[] PrivateCloudOrderFlag:<nil> PrivateCloudOrderType:<nil> PromotionCode:<nil> Properties:[] ProratedInitialCharge:<nil> ProratedOrderTotal:<nil> ProvisionScripts:[https://raw.githubusercontent.com/IBMSpectrumComputing/spectrum-schematics-cluster/master/scripts/ibm_spectrum_computing_deploy.sh] Quantity:0xc42033c7a0 QuoteName:<nil> RegionalGroup:<nil> ResourceGroupId:<nil> ResourceGroupName:<nil> ResourceGroupTemplateId:<nil> ReturnUrl:<nil> SendQuoteEmailFlag:<nil> ServerCoreCount:<nil> ServiceToken:<nil> SourceVirtualGuestId:<nil> SshKeys:[{Entity:{} SshKeyIds:[996651]}] StepId:<nil> StorageGroups:[] TaxCacheHash:<nil> TaxCompletedFlag:<nil> TechIncubatorItemPrice:<nil> TotalRecurringTax:<nil> TotalSetupTax:<nil> UseHourlyPricing:0xc42033c85e VirtualGuests:[]}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by ashishth09** [comment]
@lospringliu , looks like it is mandatory field , can you try with redundant_power_supply set to true in the schema once.

**Comment by xcliu-ca** [comment]
Adding **redundant_power_supply = true** still does not work.

ibm_compute_bare_metal.masters: Creating...
  block_storage_ids.#:     "" => "<computed>"
  datacenter:              "" => "tor01"
  domain:                  "" => "domain.com"
  file_storage_ids.#:      "" => "<computed>"
  fixed_config_preset:     "" => "S1270_32GB_2X960GBSSD_NORAID"
  hostname:                "" => "master0"
  hourly_billing:          "" => "true"
  memory:                  "" => "<computed>"
  network_speed:           "" => "1000"
  os_reference_code:       "" => "UBUNTU_16_64"
  post_install_script_uri: "" => "https://raw.githubusercontent.com/IBMSpectrumComputing/spectrum-schematics-cluster/master/scripts/ibm_spectrum_computing_deploy.sh"
  private_ipv4_address:    "" => "<computed>"
  private_network_only:    "" => "false"
  private_subnet:          "" => "<computed>"
  private_vlan_id:         "" => "<computed>"
  public_bandwidth:        "" => "<computed>"
  public_ipv4_address:     "" => "<computed>"
  public_subnet:           "" => "<computed>"
  public_vlan_id:          "" => "<computed>"
  redundant_network:       "" => "false"
  **redundant_power_supply:  "" => "true"**
  ssh_key_ids.#:           "" => "1"
  ssh_key_ids.0:           "" => "996957"
  tcp_monitoring:          "" => "false"
  unbonded_network:        "" => "false"
  user_metadata:           "" => "#!/bin/bash\n\ndeclare -i numbercomputes=0\nuseintranet=false\ndomain=domain.com\n"
Error applying plan:

1 error(s) occurred:

* ibm_compute_bare_metal.masters: 1 error(s) occurred:

* ibm_compute_bare_metal.masters: Error ordering bare metal server: SoftLayer_Exception_Order_MissingCategory: Order is missing the following category: Power Supply. (HTTP 500)

**Comment by xcliu-ca** [comment]
it worked last week

**Comment by ashishth09** [comment]
Yeah looks like it is a mandatory property now. Checking with SoftLayer.

**Comment by ashishth09** [comment]
I pushed a temporary fix with https://github.com/IBM-Bluemix/terraform-provider-ibm/commit/c39d4ffbef29da79f196b2ca7ae7f733a2e50a06.

You may try to build that branch and move on , if it is a blocker for you.

For monthly also it is a required field it seems, so if you are going for monthly then you may need to set that as true.

**Comment by xcliu-ca** [comment]
This is a blocker for **IBM Bluemix Schematics** service,  bare metal cannot be deployed in this case. I am sure it is working last week. Are there some changes from softlayer api?

Wishing to have a minor version upgrade and deploy to Schematics service if there is not work around.

**Comment by xcliu-ca** [comment]
the fix works

**Comment by ashishth09** [comment]
>Are there some changes from softlayer api?
Yes. They have made the redundant power supply mandatory now and must be provided while ordering from the API. In UI you will that pre-selected and no way to de-select. So it is a required field in the order.

**Comment by ashishth09** [comment]
Can you try again with v0.5.0? Some magic happened on the SL backend and it is simply working without the code fix I gave you. I see the field as optional now.

**Comment by xcliu-ca** [comment]
yes, 0.5.0 works again. Thanks
