### ISSUE TITLE
Interpolated output fails to resolve private_ip when on private_network_only

### ISSUE THREAD

**Issue by ashishth09** [IBM-Bluemix/terraform-provider-ibm#60]
Ported from https://github.com/IBM-Bluemix/terraform/issues/135

**Comment by frankmalin** [comment]
@ashishth09 The issue IBM-Bluemix/terraform#135 does not seem to work yet... I've tested against 0.5.0, and still see the same results.  Is there an outlook of when this will be fixed?

**Comment by ashishth09** [comment]
Hi @frankmalin ,

As discussed it never made  to the 0.5.0 release.
We are making another release this week, if you can wait. Otherwise you can build this repo's master to quickly check the fix.  

Thanks

**Comment by ashishth09** [comment]
@frankmalin ,

Please try the new release - https://github.com/IBM-Bluemix/terraform-provider-ibm/releases/tag/v0.5.1
