### ISSUE TITLE
Feature Request: CloudFoundry org to be supported as a "resource"

### ISSUE THREAD

**Issue by carltonmason** [IBM-Bluemix/terraform-provider-ibm#65]
At the moment, "ibm_org" is  just a read-only data source.  

I would like to see `ibm_org` become a resource type that allows orgs to be created, renamed, users added and removed, and assign or remove roles from users.  

I need this so I can manage orgs , spaces, users, and roles all from Terraform - that would be awesome.

**Comment by docwhat** [comment]
Yeah, I tried writing code to pull in users via spaces, and that didn't work... 

Org and Org membership management would be very useful.

**Comment by ashishth09** [comment]
Currently [data](https://ibm-bluemix.github.io/tf-ibm-docs/v0.5.0/d/space.html) source for `space`   can list users with different roles like `managers` . `auditors` and `developers`. Also one can [create](https://ibm-bluemix.github.io/tf-ibm-docs/v0.5.0/r/space.html) a space and assign role to users.
Of course these are for managing users which already exists though.

**Comment by docwhat** [comment]
Yeah, I figured that out. 


The docs are pretty good, though they should document the output/attributes. I had to guess that the `ibm` data source attribute for the name is `org`.

**Comment by docwhat** [comment]
> Also one can create a space and assign role to users. Of course these are for managing users which already exists though.

The users have to not only exist (i.e. have logged into bluemix once already) but they have to have been added to the Org first.  Adding the user to a different org in the account isn't enough.

**Comment by ashishth09** [comment]
Addressed in 0240a06aedee2a726754a401f71c20cd3a1ff0fd
